blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/NapkinStack/tool-library/discussions
    about: For anything that is not yet an identified task.
